
#include <pebble.h>
#include <stdint.h>

int32_t weather_code_to_resource_id(int32_t weather_code)
{
	time_t now_s = time(NULL);
	struct tm* now = localtime(&now_s);
	uint8_t is_night = (now->tm_hour < 7 || now->tm_hour > 19) ? 1 : 0;
	switch (weather_code) {


		case 200:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 201:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 202:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 210:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 211:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 212:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 221:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 230:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 231:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 232:
			return is_night ? RESOURCE_ID_WSYMBOL_0040_THUNDERSTORMS_NIGHT : RESOURCE_ID_WSYMBOL_0024_THUNDERSTORMS;
			break;


		case 300:
			return is_night ? RESOURCE_ID_WSYMBOL_0066_DRIZZLE_NIGHT : RESOURCE_ID_WSYMBOL_0048_DRIZZLE;
			break;


		case 301:
			return is_night ? RESOURCE_ID_WSYMBOL_0066_DRIZZLE_NIGHT : RESOURCE_ID_WSYMBOL_0048_DRIZZLE;
			break;


		case 302:
			return is_night ? RESOURCE_ID_WSYMBOL_0082_HEAVY_DRIZZLE_NIGHT : RESOURCE_ID_WSYMBOL_0081_HEAVY_DRIZZLE;
			break;


		case 310:
			return is_night ? RESOURCE_ID_WSYMBOL_0066_DRIZZLE_NIGHT : RESOURCE_ID_WSYMBOL_0048_DRIZZLE;
			break;


		case 311:
			return is_night ? RESOURCE_ID_WSYMBOL_0066_DRIZZLE_NIGHT : RESOURCE_ID_WSYMBOL_0048_DRIZZLE;
			break;


		case 312:
			return is_night ? RESOURCE_ID_WSYMBOL_0082_HEAVY_DRIZZLE_NIGHT : RESOURCE_ID_WSYMBOL_0081_HEAVY_DRIZZLE;
			break;


		case 321:
			return is_night ? RESOURCE_ID_WSYMBOL_0025_LIGHT_RAIN_SHOWERS_NIGHT : RESOURCE_ID_WSYMBOL_0009_LIGHT_RAIN_SHOWERS;
			break;


		case 500:
			return is_night ? RESOURCE_ID_WSYMBOL_0033_CLOUDY_WITH_LIGHT_RAIN_NIGHT : RESOURCE_ID_WSYMBOL_0017_CLOUDY_WITH_LIGHT_RAIN;
			break;


		case 501:
			return is_night ? RESOURCE_ID_WSYMBOL_0033_CLOUDY_WITH_LIGHT_RAIN_NIGHT : RESOURCE_ID_WSYMBOL_0017_CLOUDY_WITH_LIGHT_RAIN;
			break;


		case 502:
			return is_night ? RESOURCE_ID_WSYMBOL_0034_CLOUDY_WITH_HEAVY_RAIN_NIGHT : RESOURCE_ID_WSYMBOL_0018_CLOUDY_WITH_HEAVY_RAIN;
			break;


		case 503:
			return is_night ? RESOURCE_ID_WSYMBOL_0034_CLOUDY_WITH_HEAVY_RAIN_NIGHT : RESOURCE_ID_WSYMBOL_0018_CLOUDY_WITH_HEAVY_RAIN;
			break;


		case 504:
			return is_night ? RESOURCE_ID_WSYMBOL_0069_EXTREME_RAIN_NIGHT : RESOURCE_ID_WSYMBOL_0051_EXTREME_RAIN;
			break;


		case 511:
			return is_night ? RESOURCE_ID_WSYMBOL_0068_FREEZING_RAIN_NIGHT : RESOURCE_ID_WSYMBOL_0050_FREEZING_RAIN;
			break;


		case 520:
			return is_night ? RESOURCE_ID_WSYMBOL_0025_LIGHT_RAIN_SHOWERS_NIGHT : RESOURCE_ID_WSYMBOL_0009_LIGHT_RAIN_SHOWERS;
			break;


		case 521:
			return is_night ? RESOURCE_ID_WSYMBOL_0025_LIGHT_RAIN_SHOWERS_NIGHT : RESOURCE_ID_WSYMBOL_0009_LIGHT_RAIN_SHOWERS;
			break;


		case 522:
			return is_night ? RESOURCE_ID_WSYMBOL_0026_HEAVY_RAIN_SHOWERS_NIGHT : RESOURCE_ID_WSYMBOL_0010_HEAVY_RAIN_SHOWERS;
			break;


		case 600:
			return is_night ? RESOURCE_ID_WSYMBOL_0035_CLOUDY_WITH_LIGHT_SNOW_NIGHT : RESOURCE_ID_WSYMBOL_0019_CLOUDY_WITH_LIGHT_SNOW;
			break;


		case 601:
			return is_night ? RESOURCE_ID_WSYMBOL_0035_CLOUDY_WITH_LIGHT_SNOW_NIGHT : RESOURCE_ID_WSYMBOL_0019_CLOUDY_WITH_LIGHT_SNOW;
			break;


		case 602:
			return is_night ? RESOURCE_ID_WSYMBOL_0036_CLOUDY_WITH_HEAVY_SNOW_NIGHT : RESOURCE_ID_WSYMBOL_0020_CLOUDY_WITH_HEAVY_SNOW;
			break;


		case 611:
			return is_night ? RESOURCE_ID_WSYMBOL_0037_CLOUDY_WITH_SLEET_NIGHT : RESOURCE_ID_WSYMBOL_0021_CLOUDY_WITH_SLEET;
			break;


		case 621:
			return is_night ? RESOURCE_ID_WSYMBOL_0027_LIGHT_SNOW_SHOWERS_NIGHT : RESOURCE_ID_WSYMBOL_0011_LIGHT_SNOW_SHOWERS;
			break;


		case 701:
			return is_night ? RESOURCE_ID_WSYMBOL_0063_MIST_NIGHT : RESOURCE_ID_WSYMBOL_0006_MIST;
			break;


		case 711:
			return is_night ? RESOURCE_ID_WSYMBOL_0073_SMOKE_NIGHT : RESOURCE_ID_WSYMBOL_0055_SMOKE;
			break;


		case 721:
			return is_night ? RESOURCE_ID_WSYMBOL_0041_PARTLY_CLOUDY_NIGHT : RESOURCE_ID_WSYMBOL_0005_HAZY_SUN;
			break;


		case 731:
			return is_night ? RESOURCE_ID_WSYMBOL_0074_DUST_SAND_NIGHT : RESOURCE_ID_WSYMBOL_0056_DUST_SAND;
			break;


		case 741:
			return is_night ? RESOURCE_ID_WSYMBOL_0064_FOG_NIGHT : RESOURCE_ID_WSYMBOL_0007_FOG;
			break;


		case 800:
			return is_night ? RESOURCE_ID_WSYMBOL_0008_CLEAR_SKY_NIGHT : RESOURCE_ID_WSYMBOL_0001_SUNNY;
			break;


		case 801:
			return is_night ? RESOURCE_ID_WSYMBOL_0041_PARTLY_CLOUDY_NIGHT : RESOURCE_ID_WSYMBOL_0002_SUNNY_INTERVALS;
			break;


		case 802:
			return is_night ? RESOURCE_ID_WSYMBOL_0041_PARTLY_CLOUDY_NIGHT : RESOURCE_ID_WSYMBOL_0002_SUNNY_INTERVALS;
			break;


		case 803:
			return is_night ? RESOURCE_ID_WSYMBOL_0044_MOSTLY_CLOUDY_NIGHT : RESOURCE_ID_WSYMBOL_0043_MOSTLY_CLOUDY;
			break;


		case 804:
			return is_night ? RESOURCE_ID_WSYMBOL_0042_CLOUDY_NIGHT : RESOURCE_ID_WSYMBOL_0004_BLACK_LOW_CLOUD;
			break;


		case 900:
			return is_night ? RESOURCE_ID_WSYMBOL_0079_TORNADO : RESOURCE_ID_WSYMBOL_0079_TORNADO;
			break;


		case 901:
			return is_night ? RESOURCE_ID_WSYMBOL_0080_TROPICAL_STORM_HURRICANE : RESOURCE_ID_WSYMBOL_0080_TROPICAL_STORM_HURRICANE;
			break;


		case 902:
			return is_night ? RESOURCE_ID_WSYMBOL_0080_TROPICAL_STORM_HURRICANE : RESOURCE_ID_WSYMBOL_0080_TROPICAL_STORM_HURRICANE;
			break;


		case 903:
			return is_night ? RESOURCE_ID_WSYMBOL_0062_COLD_NIGHT : RESOURCE_ID_WSYMBOL_0046_COLD;
			break;


		case 904:
			return is_night ? RESOURCE_ID_WSYMBOL_0061_HOT_NIGHT : RESOURCE_ID_WSYMBOL_0045_HOT;
			break;


		case 905:
			return is_night ? RESOURCE_ID_WSYMBOL_0078_WINDY_NIGHT : RESOURCE_ID_WSYMBOL_0060_WINDY;
			break;


		case 906:
			return is_night ? RESOURCE_ID_WSYMBOL_0039_CLOUDY_WITH_HEAVY_HAIL_NIGHT : RESOURCE_ID_WSYMBOL_0023_CLOUDY_WITH_HEAVY_HAIL;
			break;


		default:
			return -1;
	}
}

